package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/andrea-dintino/auto-pigeon-companion/internal/release"
)

// `companion release` — the documents a release ships beside its binaries.
//
// Generated by the program rather than written beside it, because an SBOM
// somebody maintains by hand is an SBOM that is wrong within two changes. Both
// subcommands are pure: they read the built directory and this binary, and they
// hold no key and publish nothing.

const releaseUsage = `usage:
  companion release sbom [--out <file>] [--timestamp <RFC3339>]
                                    a CycloneDX document for this build
  companion release checksums --dir <dir> [--out <file>]
                                    SHA256SUMS for a built release directory

Neither signs anything. Signing is a publisher's act with a key that is not in
this program and not in CI — see README.md for the procedures, and
` + "`companion security residual`" + ` for what being unsigned currently means.
`

func runRelease(env *Env, args []string) int {
	if len(args) == 0 {
		fmt.Fprint(env.Stderr, releaseUsage)
		return 2
	}
	switch args[0] {
	case "sbom":
		return releaseSBOM(env, args[1:])
	case "checksums":
		return releaseChecksums(env, args[1:])
	}
	fmt.Fprintf(env.Stderr, "error: unknown release subcommand %q\n", args[0])
	fmt.Fprint(env.Stderr, releaseUsage)
	return 2
}

func releaseSBOM(env *Env, args []string) int {
	set := newFlagSet(env, "release sbom")
	out := set.String("out", "", "write to a file instead of stdout")
	stamp := set.String("timestamp", "", "an RFC3339 time to stamp the document with")
	if _, code, ok := parseFlags(env, set, args); !ok {
		return code
	}

	// No timestamp by default, so two runs of one build produce the same bytes
	// and the document can be published beside a digest of itself.
	var when time.Time
	if *stamp != "" {
		parsed, err := time.Parse(time.RFC3339, *stamp)
		if err != nil {
			return fail(env, fmt.Errorf("--timestamp %q is not an RFC3339 time: %w", *stamp, err))
		}
		when = parsed
	}

	document, err := release.BuildSBOM(env.Version, when)
	if err != nil {
		return fail(env, err)
	}
	encoded, err := document.Encode()
	if err != nil {
		return fail(env, err)
	}
	if *out == "" {
		env.Stdout.Write(encoded)
		return 0
	}
	if err := os.WriteFile(*out, encoded, 0o644); err != nil {
		return fail(env, err)
	}
	fmt.Fprintf(env.Stdout, "wrote %s\n", *out)
	return 0
}

func releaseChecksums(env *Env, args []string) int {
	set := newFlagSet(env, "release checksums")
	dir := set.String("dir", "", "the directory holding the built artifacts")
	out := set.String("out", "", "write to a file instead of stdout; `-` beside the artifacts")
	if _, code, ok := parseFlags(env, set, args); !ok {
		return code
	}
	if *dir == "" {
		fmt.Fprint(env.Stderr, releaseUsage)
		return 2
	}

	sums, err := release.Checksums(*dir)
	if err != nil {
		return fail(env, err)
	}
	if len(sums) == 0 {
		return fail(env, fmt.Errorf("%s holds no files to digest", *dir))
	}
	body := release.FormatChecksums(sums)

	destination := *out
	if destination == "-" {
		destination = filepath.Join(*dir, release.ChecksumFileName)
	}
	if destination == "" {
		env.Stdout.Write(body)
		return 0
	}
	if err := os.WriteFile(destination, body, 0o644); err != nil {
		return fail(env, err)
	}
	fmt.Fprintf(env.Stdout, "wrote %s (%d files)\n", destination, len(sums))
	return 0
}
