package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/andrea-dintino/auto-pigeon-companion/internal/maturity"
	"github.com/andrea-dintino/auto-pigeon-companion/internal/release"
)

// `companion release` — the documents a release ships beside its binaries.
//
// Generated by the program rather than written beside it, because an SBOM
// somebody maintains by hand is an SBOM that is wrong within two changes. Both
// subcommands are pure: they read the built directory and this binary, and they
// hold no key and publish nothing.

const releaseUsage = `usage:
  companion release sbom [--out <file>] [--timestamp <RFC3339>]
                                    a CycloneDX document for this build
  companion release checksums --dir <dir> [--out <file>]
                                    SHA256SUMS for a built release directory
  companion release support [--json]
                                    which platforms this build produces an artifact
                                    for, which have been RUN on real hardware, and
                                    which game families are still work in progress

Neither signs anything. Signing is a publisher's act with a key that is not in
this program and not in CI — see README.md for the procedures, and
` + "`companion security residual`" + ` for what being unsigned currently means.
`

func runRelease(env *Env, args []string) int {
	if len(args) == 0 {
		fmt.Fprint(env.Stderr, releaseUsage)
		return 2
	}
	switch args[0] {
	case "sbom":
		return releaseSBOM(env, args[1:])
	case "checksums":
		return releaseChecksums(env, args[1:])
	case "support":
		return releaseSupport(env, args[1:])
	}
	fmt.Fprintf(env.Stderr, "error: unknown release subcommand %q\n", args[0])
	fmt.Fprint(env.Stderr, releaseUsage)
	return 2
}

func releaseSBOM(env *Env, args []string) int {
	set := newFlagSet(env, "release sbom")
	out := set.String("out", "", "write to a file instead of stdout")
	stamp := set.String("timestamp", "", "an RFC3339 time to stamp the document with")
	if _, code, ok := parseFlags(env, set, args); !ok {
		return code
	}

	// No timestamp by default, so two runs of one build produce the same bytes
	// and the document can be published beside a digest of itself.
	var when time.Time
	if *stamp != "" {
		parsed, err := time.Parse(time.RFC3339, *stamp)
		if err != nil {
			return fail(env, fmt.Errorf("--timestamp %q is not an RFC3339 time: %w", *stamp, err))
		}
		when = parsed
	}

	document, err := release.BuildSBOM(env.Version, when)
	if err != nil {
		return fail(env, err)
	}
	encoded, err := document.Encode()
	if err != nil {
		return fail(env, err)
	}
	if *out == "" {
		env.Stdout.Write(encoded)
		return 0
	}
	if err := os.WriteFile(*out, encoded, 0o644); err != nil {
		return fail(env, err)
	}
	fmt.Fprintf(env.Stdout, "wrote %s\n", *out)
	return 0
}

func releaseChecksums(env *Env, args []string) int {
	set := newFlagSet(env, "release checksums")
	dir := set.String("dir", "", "the directory holding the built artifacts")
	out := set.String("out", "", "write to a file instead of stdout; `-` beside the artifacts")
	if _, code, ok := parseFlags(env, set, args); !ok {
		return code
	}
	if *dir == "" {
		fmt.Fprint(env.Stderr, releaseUsage)
		return 2
	}

	sums, err := release.Checksums(*dir)
	if err != nil {
		return fail(env, err)
	}
	if len(sums) == 0 {
		return fail(env, fmt.Errorf("%s holds no files to digest", *dir))
	}
	body := release.FormatChecksums(sums)

	destination := *out
	if destination == "-" {
		destination = filepath.Join(*dir, release.ChecksumFileName)
	}
	if destination == "" {
		env.Stdout.Write(body)
		return 0
	}
	if err := os.WriteFile(destination, body, 0o644); err != nil {
		return fail(env, err)
	}
	fmt.Fprintf(env.Stdout, "wrote %s (%d files)\n", destination, len(sums))
	return 0
}

// releaseSupport prints the two axes a release note has to keep apart.
//
// BUILT is what `build/release.sh` produces. NATIVELY VERIFIED is what somebody
// ran the acceptance kit on and sent a bundle back from. A cross-compiled
// artifact is a real artifact and stays in the list; what it does not get is a
// claim nobody checked. `build_only` and `manual_pending` are printed as
// themselves and are never rendered as a pass.
//
// The game-family half is `internal/maturity`'s, unchanged: Quake II and Quake
// III are work in progress and say so in the same sentence every other surface
// prints.
func releaseSupport(env *Env, args []string) int {
	set := newFlagSet(env, "release support")
	asJSON := set.Bool("json", false, "print the tables as JSON")
	if _, code, ok := parseInterspersed(env, set, args); !ok {
		return code
	}
	rows, err := release.Rows()
	if err != nil {
		return fail(env, err)
	}
	families := make([]map[string]string, 0, len(maturity.Families()))
	for _, family := range maturity.Families() {
		statement := maturity.Of(family)
		families = append(families, map[string]string{
			"family": statement.Family, "state": string(statement.State),
			"message": statement.Message,
		})
	}
	if *asJSON {
		encoded, err := json.MarshalIndent(map[string]any{
			"schema": release.SupportSchema, "platforms": rows, "families": families,
		}, "", "  ")
		if err != nil {
			return fail(env, err)
		}
		fmt.Fprintln(env.Stdout, string(encoded))
		return 0
	}

	fmt.Fprintln(env.Stdout, "platforms — an artifact is built for each of these:")
	for _, row := range rows {
		built := "built"
		if !row.Built {
			built = "not built"
		}
		fmt.Fprintf(env.Stdout, "  %-15s %-10s %-15s %s\n", row.Target, built, row.State, row.Note)
		for _, verification := range row.Verifications {
			fmt.Fprintf(env.Stdout, "  %-15s   %s %s %s\n", "",
				verification.Verdict, verification.ProducedAt, verification.BundleID)
		}
	}
	fmt.Fprint(env.Stdout, `
  native_pass     something ran the acceptance kit on that hardware and it passed
  native_fail     something ran it there and it did not pass
  manual_pending  a machine exists and nobody has run it yet — NOT a pass
  build_only      an artifact is produced and no native host is declared — NOT a pass
  unsupported     no artifact is produced for that target

`)
	fmt.Fprintln(env.Stdout, "game families:")
	for _, family := range families {
		state := family["state"]
		if state == "work_in_progress" {
			fmt.Fprintf(env.Stdout, "  %-8s experimental  %s\n", family["family"], family["message"])
		} else {
			fmt.Fprintf(env.Stdout, "  %-8s %s\n", family["family"], state)
		}
	}
	fmt.Fprintln(env.Stdout, `
A built artifact is a real artifact: it is produced, checksummed and published.
What it is not, on its own, is evidence that the program works on that hardware.
Run `+"`acceptance/run-acceptance.sh`"+` or `+"`acceptance/run-acceptance.ps1`"+` there and send the bundle back.`)
	return 0
}
