#!/usr/bin/env python3
"""Generate the Q3_011 packaging fixture. Everything here is computed by this
script: no file is copied from any game, map or asset pack. Released under CC0.
usage: gen_fixture.py <out-dir>"""
import os, struct, sys, zipfile, math

out = sys.argv[1]
assets = os.path.join(out, "assets")

def write(rel, data, root=assets):
    path = os.path.join(root, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)

def tga(size, pixel):
    header = struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, size, size, 24, 0x20)
    body = bytearray()
    for y in range(size):
        for x in range(size):
            r, g, b = pixel(x, y)
            body += bytes((b, g, r))
    return header + bytes(body)

def checker(a, b, cell):
    return lambda x, y: a if ((x // cell) + (y // cell)) % 2 == 0 else b

def bricks(x, y):
    row = y // 8
    mortar = (y % 8 == 0) or ((x + (row % 2) * 8) % 16 == 0)
    return (60, 58, 54) if mortar else (150 + (row * 7) % 20, 84, 60)

write("textures/apq3011/wall.tga", tga(32, bricks))
write("textures/apq3011/floor.tga", tga(32, checker((90, 96, 104), (70, 74, 82), 8)))
write("textures/apq3011/ceiling.tga", tga(32, checker((120, 120, 110), (104, 104, 96), 16)))
write("textures/apq3011/glow_stage.tga", tga(32, lambda x, y: (255, 200 - 4 * abs(16 - x), 40)))
write("textures/apq3011/glow_editor.tga", tga(32, checker((255, 220, 0), (0, 0, 0), 4)))
write("models/apq3011/crate.tga", tga(32, checker((140, 100, 50), (110, 78, 40), 4)))
write("models/apq3011/beacon.tga", tga(32, checker((40, 160, 200), (20, 90, 120), 2)))

write("scripts/apq3011.shader", b"""// Auto-Pigeon Q3_011 packaging fixture. Original work, CC0.
textures/apq3011/glow
{
	qer_editorimage textures/apq3011/glow_editor.tga
	q3map_surfacelight 400
	surfaceparm nomarks
	{
		map textures/apq3011/glow_stage.tga
		rgbGen identity
	}
}
""")

write("LICENSE-apq3011.txt", b"""Auto-Pigeon Q3_011 packaging fixture.
Every file in this archive was generated by a script written for Auto-Pigeon.
No file is derived from any game, map or third-party asset.
Dedicated to the public domain under CC0 1.0 Universal.
""")

def name(text, width):
    raw = text.encode("ascii")
    return raw + b"\0" * (width - len(raw))

def md3(model_name, shader, half):
    corners = [(-half, -half, 0), (half, -half, 0), (half, half, 0), (-half, half, 0),
               (-half, -half, 2 * half), (half, -half, 2 * half), (half, half, 2 * half), (-half, half, 2 * half)]
    quads = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
    normals = [(0, 0, -1), (0, 0, 1), (0, -1, 0), (1, 0, 0), (0, 1, 0), (-1, 0, 0)]
    verts, sts, tris = [], [], []
    for quad, normal in zip(quads, normals):
        base = len(verts)
        for corner, st in zip(quad, [(0, 0), (1, 0), (1, 1), (0, 1)]):
            verts.append((corners[corner], normal))
            sts.append(st)
        tris += [(base, base + 2, base + 1), (base, base + 3, base + 2)]
    def encode_normal(n):
        x, y, z = n
        lat = int(round(math.atan2(y, x) * 255 / (2 * math.pi))) & 255
        lng = int(round(math.acos(z) * 255 / (2 * math.pi))) & 255
        return (lat << 8) | lng
    shaders = name(shader, 64) + struct.pack("<i", 0)
    triangles = b"".join(struct.pack("<3i", *t) for t in tris)
    st = b"".join(struct.pack("<2f", *s) for s in sts)
    xyz = b"".join(struct.pack("<3hH", int(p[0] * 64), int(p[1] * 64), int(p[2] * 64), encode_normal(n)) for p, n in verts)
    surface_header = 4 + 64 + 10 * 4
    ofs_shaders = surface_header
    ofs_triangles = ofs_shaders + len(shaders)
    ofs_st = ofs_triangles + len(triangles)
    ofs_xyz = ofs_st + len(st)
    ofs_end = ofs_xyz + len(xyz)
    surface = (b"IDP3" + name("box", 64) + struct.pack("<10i", 0, 1, 1, len(verts), len(tris),
               ofs_triangles, ofs_shaders, ofs_st, ofs_xyz, ofs_end) + shaders + triangles + st + xyz)
    frame = struct.pack("<10f", -half, -half, 0, half, half, 2 * half, 0, 0, 0, half * 2) + name("frame0", 16)
    header_size = 4 + 4 + 64 + 9 * 4
    ofs_frames = header_size
    ofs_tags = ofs_frames + len(frame)
    ofs_surfaces = ofs_tags
    total = ofs_surfaces + len(surface)
    header = b"IDP3" + struct.pack("<i", 15) + name(model_name, 64) + struct.pack(
        "<9i", 0, 1, 0, 1, 0, ofs_frames, ofs_tags, ofs_surfaces, total)
    return header + frame + surface

write("models/apq3011/crate.md3", md3("models/apq3011/crate.md3", "models/apq3011/crate.tga", 16))
write("models/apq3011/beacon.md3", md3("models/apq3011/beacon.md3", "models/apq3011/beacon.tga", 8))

samples = bytes(128 + int(60 * math.sin(i * 2 * math.pi * 220 / 11025)) for i in range(2205))
wav = (b"RIFF" + struct.pack("<I", 36 + len(samples)) + b"WAVEfmt " +
       struct.pack("<IHHIIHH", 16, 1, 1, 11025, 11025, 1, 8) + b"data" + struct.pack("<I", len(samples)) + samples)
write("sound/apq3011/hum.wav", wav)

def box(x0, y0, z0, x1, y1, z1, shader):
    faces = [
        ((x0, y1, z1), (x1, y1, z1), (x1, y0, z1)),
        ((x0, y0, z0), (x1, y0, z0), (x1, y1, z0)),
        ((x1, y0, z1), (x1, y1, z1), (x1, y1, z0)),
        ((x0, y1, z1), (x0, y0, z1), (x0, y0, z0)),
        ((x1, y1, z1), (x0, y1, z1), (x0, y1, z0)),
        ((x0, y0, z1), (x1, y0, z1), (x1, y0, z0)),
    ]
    lines = ["{"]
    for a, b, c in faces:
        lines.append("( %d %d %d ) ( %d %d %d ) ( %d %d %d ) %s 0 0 0 0.5 0.5 0 0 0" % (*a, *b, *c, shader))
    lines.append("}")
    return "\n".join(lines)

world = [
    box(-272, -272, -16, 272, 272, 0, "apq3011/floor"),
    box(-272, -272, 256, 272, 272, 272, "apq3011/ceiling"),
    box(-272, -272, 0, -256, 272, 256, "apq3011/wall"),
    box(256, -272, 0, 272, 272, 256, "apq3011/wall"),
    box(-256, -272, 0, 256, -256, 256, "apq3011/wall"),
    box(-256, 256, 0, 256, 272, 256, "apq3011/wall"),
    box(-32, -32, 240, 32, 32, 256, "apq3011/glow"),
]
entity = lambda pairs, brushes=(): "{\n" + "\n".join('"%s" "%s"' % p for p in pairs) + ("\n" + "\n".join(brushes) if brushes else "") + "\n}\n"
map_text = "// Auto-Pigeon Q3_011 packaging fixture. Original work, CC0.\n"
map_text += entity([("classname", "worldspawn"), ("message", "Auto-Pigeon Q3_011 packaging fixture")], world)
map_text += entity([("classname", "info_player_deathmatch"), ("origin", "0 -128 32"), ("angle", "90")])
map_text += entity([("classname", "light"), ("origin", "0 0 192"), ("light", "300")])
map_text += entity([("classname", "misc_model"), ("origin", "128 128 0"), ("model", "models/apq3011/crate.md3")])
map_text += entity([("classname", "func_static"), ("model2", "models/apq3011/beacon.md3")],
                   [box(-144, 112, 0, -112, 144, 32, "apq3011/wall")])
map_text += entity([("classname", "target_speaker"), ("origin", "0 0 64"), ("noise", "sound/apq3011/hum.wav"), ("spawnflags", "1")])
write("q3011_room.map", map_text.encode("ascii"), root=os.path.join(out, "src"))

# The synthetic licensed PK3: stored, sorted, fixed timestamps.
pk3 = os.path.join(out, "zz_apq3011_assets.pk3")
members = []
for directory, _, files in os.walk(assets):
    for f in files:
        full = os.path.join(directory, f)
        members.append((os.path.relpath(full, assets).replace(os.sep, "/"), full))
with zipfile.ZipFile(pk3, "w", zipfile.ZIP_STORED) as z:
    for rel, full in sorted(members):
        info = zipfile.ZipInfo(rel, date_time=(1980, 1, 1, 0, 0, 0))
        info.external_attr = 0
        info.create_system = 0
        z.writestr(info, open(full, "rb").read())
print("wrote", out, len(members), "asset files")
